server:
  port: 8888
spring:
  application:
    name: microservice-config-server-eureka-authenticating
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config
  profiles:
    active: native
eureka:
  client:
    service-url:
      defaultZone: http://admin:123456@localhost:8761/eureka/
security:
  basic:
    enabled: true
  user:
    name: admin
    password: admin