spring:
  application:
    name: microservice-customer
server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://admin:123456@localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instanceId: ${spring.application.name}:${spring.application.instance_id:${server.port}}