spring:
  application:
    name: microservice-movie
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-center
      name: movie
      profile: dev
server:
  port: 8081
eureka:
  client:
    service-url:
      defaultZone: http://admin:123456@localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}

# Disable eureka server,it will get register list from 'listOfServers'
#ribbon:
#  eureka:
#   enabled: false
#microservice-customer:
#  ribbon:
#    listOfServers: http://localhost:8080
microservice-customer2:
  ribbon:
#    listOfServers: http://localhost:8085,http://localhost:8086
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
