server:
  port: 9091
spring:
  application:
    name: microservice-config-client-eureka-encryption-rsa
  cloud:
    config:
      name: test
      discovery:
        enabled: true
        service-id: microservice-config-server-encryption-rsa
eureka:
  client:
    service-url:
      defaultZone: http://admin:123456@localhost:8761/eureka/