haha:
  user:
    name: tony
    password: '{cipher}AQAL5c90zl1Q3ncBr4V82LtwC3YKlWd09mDn9XpUIzeQYCpfsuExgqfXKobnBqLM5diAJFfUaWJQJLETzGhz0AnuDLxmc6tEuZAEtHtBHA3APOmRI046sEcGK+F5IoLONJEWbvnwwyacHo2bRPKMaa7YEmhm2t+6Nf7H1A9/rXoIMkbZaHwwN6g23VBn1HGRAAI9TeIi3Gw46uHTzVqheXW7OzCrV4vsx/0UtVXkKn9LyhiLL3Ojw7z45OofkVapmYx15W9QFHfvOnbIST/vDkUXpnvZrdwNKCdEkqSryqNqEXrewohkwe+KHAJI0DWVI+x7RtUCZnuPMc3gEes9zSEehbHCLmm195knalPgDyEWqXyaxENMuvN0mYRbPtDxMJk='