server:
  port: 8888
spring:
  application:
    name: config-center
  profiles:
      active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config
eureka:
  client:
    service-url:
      defaultZone: http://admin:123456@localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}