server:
  port: 8888
spring:
  application:
    name: microservice-config-server-encryption-rsa
  cloud:
      config:
        server:
          native:
            search-locations: classpath:/config
  profiles:
    active: native
eureka:
  client:
    service-url:
      defaultZone: http://admin:123456@localhost:8761/eureka/
########################### 对称加密   ###########################
#encrypt:
#  key: foo
########################### 非对称加密 ###########################
# Build a *.keystore file with java keytool.
# keytool -genkey -alias server -keypass server -keyalg RSA -keysize 1024 -validity 365 -keystore server.jks -storepass qazxsw -dname "CN=TonyLiu, OU=Demo, O=Demo, L=Shanghai, ST=Shanghai, C=ZH"
encrypt:
  key-store:
    location: classpath:/server.jks    # 本地
    password: letmein                  # 对应的storepass
    alias: mytestkey                   # 别名
    secret: changeme                   # 对应keypass