server:
  port: 8082
spring:
  application:
    name: microservice-config-client-refresh-bus
    index: ${random.value}
  cloud:
    config:
      discovery:
        enabled: true
        service-id: microservice-config-server-git
      name: demo
      profile: dev
    bus:
      trace:
        enabled: true
      destination: springCloudBus
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
eureka:
  client:
    service-url:
      defaultZone: http://admin:123456@localhost:8761/eureka/